services:
  - type: web
    name: cloud-rsvp-tracker
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
